BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Gauge] ADD [imageId] INT;

-- CreateTable
CREATE TABLE [dbo].[Image] (
    [id] INT NOT NULL IDENTITY(1,1),
    [url] NVARCHAR(1000) NOT NULL,
    [ownerType] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Image_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Image_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Gauge] ADD CONSTRAINT [Gauge_imageId_fkey] FOREIGN KEY ([imageId]) REFERENCES [dbo].[Image]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
